<template>
  <v-container>
    <v-layout
      align-center
      justify-center
      row
      fill-height
    >

      <v-flex
        md6
        sm8
        xs11
      >
        <v-card class="elevation-12">
          <v-alert
            :value="!!error"
            type="warning"
          >
            {{error.error}}
          </v-alert>

          <v-toolbar
            dark
            color="primary"
          >
            <v-toolbar-title>Atualize sua senha</v-toolbar-title>
            <v-spacer></v-spacer>

          </v-toolbar>
          <v-card-text>
            <v-form>
              <v-text-field
                id="password"
                prepend-icon="lock"
                name="password"
                label="Senha"
                type="password"
                v-model.trim.lazy="password"
              ></v-text-field>
              <v-checkbox
                :label="`Lembre-se`"
                color="primary"
                v-model="rememberMe"
              ></v-checkbox>
            </v-form>
          </v-card-text>
          <v-card-actions>
            <v-layout
              align-center
              justify-center
              row
            >
              <v-btn
                @click="onSubmit"
                color="primary"
              >Enviar</v-btn>
            </v-layout>
          </v-card-actions>
        </v-card>
      </v-flex>
    </v-layout>
  </v-container>
</template>
